### ISSUE TITLE
Cannot provide 'Environment' value

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph_assets#495]
Cannot provide Envornment value because of its empty value. 
However /admin/discovery/environment/  contains this value.
Are they the same "environments" or they are not related.
If not, where "Asset Environment" value should be filled in?

![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/4882543/63ba64fa-6357-11e4-88a7-685517896eec.JPG)

**Comment by vi4m** [comment]
Still open?

**Comment by ar4s** [comment]
``Device Environment`` is proxy to CI with custom manager.
I can't reproduce this bug in develop. I think it is resolved.
