### ISSUE TITLE
Support management in ralph

### ISSUE THREAD

**Issue by inc0** [allegro/ralph_assets#81]
===========================
Support management in ralph assets
===========================

Abstract
**********

We got feature request for support contracts management in ralph-assets. Most of assets has certain support contract assigned to them, with certain dates and suport types. We need tool which will help us manage it in more convenient way, i.e. sending email when support of certain assets ends.

Implementation
******************

This sub-module to assets will contain 2 new views and new element in asset detail view.

View 1: Support contract list:

* This view will display list of support contracts and some basic details of them like whether or not its active or id.

* Will contain list filters. User will be able to filter out records. For example:
    * to show only active contracts.
    * price range
    * date range
    * name/id (maybe fuzzy logic search field?)

View 2: Contract detail page:

* This view will allow users to edit contract detail, add new contract etc.

* Will contain form with all necessary fields to create and edit new support contract.

* Pretty much everything from database model should be editable

3: Support box in detailed asset view.

* User will be able to select and add new support contract to this asset. Each asset may have more than one support contract asigned.

* Box should show read-only details of support contract (dates, escalation path etc. maybe ajax autoloading on-select?), link to contract detail page and fields for asset-specific info (fields from m2m relation table).

DB Model
***********

We need to work on 2 models:
1. SupportContract:
    
    This model represents each support contract. Fields:
    1. Contract id - CharField containing contract identifier
    2. Name - name of contract
    3. Description
    4. Attachment - user need to be able to save file attachments.
    5. Cost - cost for given support
    6. Dates - from-to
    7. Notification period - email for example 2 weeks before contract ends.
    8. Escalation path - simple text field with howto of problem escalation, support contacts etc.
    9. Contract terms - simple text field
    10. Additional notes
    11. Support supplier - company which provides support described by this contract
    12. SLA type - text field with sla details for this assets

**Comment by vi4m** [comment]
Already resolved. closing.
